name: Deploy to GitHub Pages

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # if: github.repository == 'lunchbreakdev/lbd-components' && github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'documentation')
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js 20.x
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup Pages
        # https://github.com/actions/configure-pages
        uses: actions/configure-pages@v5

      - name: Persist Eleventy .cache
        # https://github.com/actions/cache
        uses: actions/cache@v4
        with:
          path: ./.cache
          key: ${{ runner.os }}-eleventy-fetch-cache

      - name: Install Dependencies
        run: yarn

      - name: Build Docs
        run: yarn docs:build

      - name: Upload artifact
        # https://github.com/actions/upload-pages-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site

  deploy:
    name: Deploy
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # https://github.com/actions/deploy-pages
        uses: actions/deploy-pages@v4
